name: "agl"
version: "1.0"
copyright: "Lobarev Yuriy - 2015"
kladr: "57500faf0a69decc7d8b4568"
password: "8823423977742"
updateKey: "sekh234khk234hk22"
debug: { errors: 1, message: 1, console: 1 }
git_repository: "git@github.com:anyks/agl.git"
config_dir: "config"
rc_dir: "/usr/local/etc/rc.d"
git_dir: "/var/www/git"
work_dir: "/var/www"
logs_dir: "/var/www/logs"
rmdirs:
  - "models"
  - "server"
  - "api"
  - "agents"
  - "{{ config_dir }}"

cpdirs:
  - "models"
  - "server"
  - "api"
  - "agents"

# Users
user: "www"
group: "freebsd"

# Devel scripts
nodejs_bin: "/usr/local/bin/node"
forever_bin: "/var/www/node_modules/forever/bin/forever"
stack_size: "2097151"
min_uptime: "3000"
sleep_time: "2000"
server_host: "107.170.122.222:3320"
redis_host: "/tmp/redis.sock"
redis_pass: "37493745979443"