name: "agl"
version: "1.0"
copyright: "Lobarev Yuriy - 2016"
kladr: "57500faf0a69decc7d8b4568"
debug: { errors: 1, message: 1 }
git_repository: "git@github.com:anyks/agl.git"
config_dir: "config"
git_dir: "/var/www/git"
work_dir: "/var/www"
logs_dir: "/var/www/logs"
rmdirs:
  - "models"
  - "server"
  - "api"
  - "agents"
  - "{{ config_dir }}"

cpdirs:
  - "models"
  - "server"
  - "api"
  - "agents"
